# Generated by Django 5.0.3 on 2024-05-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
