# Generated by Django 5.0.3 on 2024-05-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_kitchen_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
