# Generated by Django 4.2 on 2024-05-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, unique_for_date='created'),
        ),
    ]
