# Generated by Django 5.0.6 on 2024-06-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_kitchen_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='service_fee_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='service_fee_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
