# Generated by Django 5.0.6 on 2024-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_kitchen_service_fee_amount_kitchen_service_fee_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('employee', 'Employee')], default='user', max_length=255),
        ),
    ]
