# Generated by Django 5.0.3 on 2024-05-05 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='users.kitchen'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kitchen'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to='main.foodcategory'),
        ),
        migrations.AddField(
            model_name='foodvariant',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.food'),
        ),
        migrations.AddField(
            model_name='menu',
            name='foods',
            field=models.ManyToManyField(related_name='menus', to='main.food'),
        ),
        migrations.AddField(
            model_name='menu',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='users.kitchen'),
        ),
        migrations.AddField(
            model_name='payment',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.kitchen'),
        ),
    ]
