# Generated by Django 4.0 on 2024-05-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='foods',
            field=models.ManyToManyField(related_name='menus', to='main.Food'),
        ),
    ]
