# Generated by Django 4.0 on 2024-05-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menu_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
