# Generated by Django 4.2 on 2024-05-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
