# Generated by Django 5.0.6 on 2024-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_foodcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='default-food-image.jpg', upload_to='food/'),
        ),
    ]
