# Generated by Django 4.2.8 on 2023-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='registered_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
