# Generated by Django 5.0.6 on 2024-06-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='service_fee',
            field=models.IntegerField(default=0),
        ),
    ]
