# Generated by Django 5.0.6 on 2024-06-16 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
