# Generated by Django 5.0.3 on 2024-05-05 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField(default=4)),
                ('views', models.PositiveIntegerField(default=0)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='table_qr_codes')),
                ('status', models.CharField(choices=[('available', 'Bo`sh'), ('occupied', 'Band'), ('reserved', 'Zaxira')], default='available', max_length=10)),
            ],
        ),
    ]
