# Generated by Django 5.0.6 on 2024-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
